apiVersion: v1
kind: Service
metadata:
  namespace: devkit-ns
  name: orders-service
  labels:
    name: orders-service
    app: snappy-app
    tier: api
spec:
  type: ClusterIP
  selector:
    name: orders-pod
    app: snappy-app
    tier: api
  ports:
    - port: 443
      targetPort: 443