apiVersion: v1
kind: Service
metadata:
  namespace: logistics-base-ns
  name: portainer-service
  labels:
    name: portainer-service
    app: logistics-app
    tier: base
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30103
  selector:
    name: portainer-pod
    app: logistics-app
    tier: base   