apiVersion: v1
kind: Service
metadata:
  namespace: logistics-base-ns
  name: rabbitmq-service
  labels:
    name: rabbitmq-service
    app: logistics-app
    tier: base
spec:
  type: NodePort
  ports:
    - port: 15671
      targetPort: 15671
      nodePort: 30103
      name: rabbitmq-15671
    - port: 15672
      targetPort: 15672
      nodePort: 30104
      name: rabbitmq-15672
    - port: 5672
      targetPort: 5672
      nodePort: 30105
      name: rabbitmq-5672
  selector:
    name: rabbitmq-pod
    app: logistics-app
    tier: base