apiVersion: v1
kind: Service
metadata:
  namespace: logistics-api-ns
  name: file-store-service
  labels:
    name: file-store-service
    app: logistics-app
    tier: apiVersion
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
  selector:
    name: file-store-pod
    app: logistics-app
    tier: api