apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logistics-api-ns
  name: gateway-deploy
  labels:
    name: gateway-deploy
    app: logistics-app
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:      
      name: gateway-pod
      app: logistics-app
      tier: api
  template:
    metadata:
      namespace: logistics-api-ns
      name: gateway-pod
      labels:
        name: gateway-pod
        app: logistics-app
        tier: api
    spec:
      containers:
        - name: gateway
          image: devkit.gateway:latest
          ports:
            - containerPort: 443
    
