apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logistics-api-ns
  name: orders-deploy
  labels:
    name: orders-deploy
    app: logistics-app
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders-pod
      app: logistics-app
      tier: api
  template:
    metadata:
      namespace: logistics-api-ns
      name: orders-pod
      labels:
        name: orders-pod
        app: logistics-app
        tier: api
    spec:
      containers:
        - name: orders
          image: logistics.orders:latest
          ports:
            - containerPort: 443
        
    
    