apiVersion: v1
kind: Service
metadata:
  namespace: logistics-api-ns
  name: vehicles-service
  labels:
    name: vehicles-service
    app: logistics-app
    tier: api
spec:
  type: ClusterIP
  selector:
    name: vehicles-pod
    app: logistics-app
    tier: api
  ports:
    - port: 443
      targetPort: 443