apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devkit-ns
  name: azure-devops-deploy-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["secrets", "configmaps", "persistentvolumeclaims", "deployments", "replicasets", "pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-devops-deploy-manager
  namespace: devkit-ns
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-devops-deploy-role
  apiGroup: rbac.authorization.k8s.io
