
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devkit-ns
  name: redisinsight-deployment
  labels:
    app: snappy
    name: redisinsight-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: snappy
      name: redisinsight-pod
  template: 
    metadata:
      namespace: devkit-ns
      name: redisinsight-pod
      labels:
        app: snappy
        name: redisinsight-pod

    spec:
      containers:
      - name: redisinsight
        image: redislabs/redisinsight:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.5"
        ports: 
          - containerPort: 8001
